<?php
/**
 * Created by Tobias Ranft <coded@ranft.biz> 2015
 */
?><div class="container">
    <div class="jumbotron">
        <div class="container">
            <h1>Sample implementation of a coffeebar cart for TastyCoffee</h1>
            <div>
                The TastyCoffee bar sells Espresso, Cappuccino, Latte, Mocca and Americano.
                The cart shall collect customers order, calculate sums and provides a list of needed ingredients.
            </div>
        </div>
    </div>
    <div>
        coming soon...
    </div>
</div>
