<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <?php // The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags ?>
    <title>php.codesamples by Tobias Ranft (2015)</title>

    <?php // Latest compiled and minified CSS ?>
    <link rel="stylesheet" href="/offline/css/bootstrap.min.css">

    <?php // Theme ?>
    <link rel="stylesheet" href="/offline/css/bootstrap-theme.min.css">

</head>
<body>
<?php

    echo $this->getView()->get('content');

?>
<?php // jQuery ?>
<script src="/offline/jquery.min.js"></script>
<?php // Latest compiled and minified JavaScript ?>
<script src="/offline/js/bootstrap.min.js"></script>
</body>
</html>