<div>
    <h1>php.codesamples by Tobias Ranft</h1>
    <p>
        Some stuff to show my ability to write clean, readable and maintable code in PHP.
        All sourcecode is available at <a href="https://github.com/devtop/php.codesamples">github.com</a>.
        Let me know, if you find it interesting. <span class="insertmail"></span>
        I appreciate any kind of feedback.
    </p>
    <p>
        My version of the common known coding task Fizz Buzz.
        I chose to solve it in an object oriented way.
        Usually I would use OOP for such a small task.
        Just as a little finger excercise.
        <a href="/fizzbuzz">Fizz Buzz</a>
    </p>

</div>
