<div class="jumbotron">
    <div class="container">
        <h1>php.codesamples</h1> by Tobias Ranft
        <p>
            Some stuff to show my ability to write clean, readable and maintable code in PHP.
            All sourcecode is available at <a href="https://github.com/devtop/php.codesamples">github.com</a>.
            Let me know, if you find it interesting. <span class="insertmail"></span>
            I appreciate any kind of feedback.
        </p>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <h2>Fizz Buzz</h2>
            <p>
                My version of the common known coding task Fizz Buzz.
                I chose to solve it in an object oriented way.
                Usually I would use OOP for such a small task.
                Just as a little finger excercise.
            </p>
            <p>
                <a href="/fizzbuzz" role="button">Fizz Buzz</a>
            </p>
        </div>
        <div class="col-md-4">
            <h2>Basic Framework</h2>
            <p>
                Some simple implementation to publish this site.
                It includes class autoloading, HTTP router, PHP renderer and some resolvers.
                All is cleanly test covered and implemented with TDD.
            </p>
            <p>
                <a href="https://github.com/devtop/php.codesamples/tree/master/src/Standard"
                   role="button" target="_blank">view source @github.com</a>
            </p>
        </div>
        <div class="col-md-4">
            <h2>Coffeebar</h2>
            <p>
                Work in progress...
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <h2>Prime Numbers</h2>
            <p>
                Coming soon....
            </p>
        </div>
        <div class="col-md-4">
            <h2>Sequence Problem</h2>
            <p>
                Coming soon...
            </p>
        </div>
    </div>
</div>
